name: Build code

on: push

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Build SWC
        run: yarn build:swc
      - name: Build storybook
        run: yarn storybook:build
